apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "sa-p5" | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: "comicrent"
    