apiVersion: v1
kind: Secret
metadata:
  name: comicrent-postgresql-secret
  namespace: {{ .Values.namespace | default "sa-p5" | quote }}
  labels:
    app.kubernetes.io/part-of: "comicrent"
type: Opaque
stringData:
  postgres-password: {{ required "global.secrets.postgresPassword es obligatorio" .Values.global.secrets.postgresPassword | quote }}
  password: {{ required "global.secrets.postgresUserPassword es obligatorio" .Values.global.secrets.postgresUserPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: comicrent-rabbitmq-secret
  namespace: {{ .Values.namespace | default "sa-p5" | quote }}
  labels:
    app.kubernetes.io/part-of: "comicrent"
type: Opaque
stringData:
  rabbitmq-password: {{ required "global.secrets.rabbitmqPassword es obligatorio" .Values.global.secrets.rabbitmqPassword | quote }}