apiVersion: v1
kind: Secret
metadata:
  name: comicrent-postgresql-secret
  namespace: {{ .Values.namespace | default "sa-p5" | quote }}
  labels:
    app.kubernetes.io/part-of: "comicrent"
type: Opaque
stringData:
  postgres-password: {{ required "postgresqlSecrets.postgresPassword es obligatorio" .Values.postgresqlSecrets.postgresPassword | quote }}
  password: {{ required "postgresqlSecrets.userPassword es obligatorio" .Values.postgresqlSecrets.userPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: comicrent-rabbitmq-secret
  namespace: {{ .Values.namespace | default "sa-p5" | quote }}
  labels:
    app.kubernetes.io/part-of: "comicrent"
type: Opaque
stringData:
  rabbitmq-password: {{ required "rabbitmqSecrets.password es obligatorio" .Values.rabbitmqSecrets.password | quote }}