apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rentals-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "rentals-service.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "rentals-service.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "rentals-service.selectorLabels" . | nindent 8 }}

      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

    spec:
      serviceAccountName: {{ include "rentals-service.fullname" . }}
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: rentals-service

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "rentals-service.fullname" . }}-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comicrent-postgresql-secret
                  key: password

            - name: DATABASE_URL
              value: "postgresql+psycopg://comicrent_user:$(DB_PASSWORD)@comicrent-postgresql:5432/rentals_db"

            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comicrent-rabbitmq-secret
                  key: rabbitmq-password

          resources:
            {{- toYaml .Values.resources | nindent 12 }}