apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comics-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "comics-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "comics-service.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "comics-service.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

    spec:
      containers:
        - name: comics-service

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "comics-service.fullname" . }}-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comicrent-postgresql-secret
                  key: password

            - name: DATABASE_URL
              value: "postgresql://comicrent_user:$(DB_PASSWORD)@comicrent-postgresql:5432/comics_db?schema=public"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}