FROM python:3.12-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install \
    --no-cache-dir \
    --target=/app/dependencies \
    -r requirements.txt

COPY app ./app


FROM gcr.io/distroless/python3-debian12:nonroot

WORKDIR /app

COPY --from=builder /app /app

ENV PYTHONPATH=/app/dependencies

EXPOSE 8001

CMD ["-m","uvicorn","app.main:app","--host","0.0.0.0","--port","8001"]