services:

  # ==========================================
  # AUTH DATABASE
  # ==========================================

  auth-db:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}

    ports:
      - "${AUTH_DB_PORT}:5432"

    volumes:
      - auth_db_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  # ==========================================
  # AUTH SERVICE
  # ==========================================

  auth-service:
    build:
      context: ./services/auth-service

    restart: unless-stopped

    environment:
      PORT: ${AUTH_SERVICE_PORT}

      DATABASE_URL: postgresql://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth-db:5432/${AUTH_DB_NAME}?schema=public

      JWT_SECRET: ${AUTH_JWT_SECRET}
      ENCRYPTION_KEY: ${AUTH_ENCRYPTION_KEY}

      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_REFRESH_TIME_SECONDS: ${JWT_REFRESH_TIME_SECONDS}

    ports:
      - "${AUTH_SERVICE_PORT}:3001"

    depends_on:
      auth-db:
        condition: service_healthy

    command:
      >
        sh -c "
        npx prisma migrate deploy &&
        npm run start:prod
        "


  # ==========================================
  # COMICS DATABASE
  # ==========================================

  comics-db:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${COMICS_DB_USER}
      POSTGRES_PASSWORD: ${COMICS_DB_PASSWORD}
      POSTGRES_DB: ${COMICS_DB_NAME}

    ports:
      - "${COMICS_DB_PORT}:5432"

    volumes:
      - comics_db_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${COMICS_DB_USER} -d ${COMICS_DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  # ==========================================
  # COMICS SERVICE
  # ==========================================

  comics-service:
    build:
      context: ./services/comics-service

    restart: unless-stopped

    environment:
      PORT: ${COMICS_SERVICE_PORT}

      DATABASE_URL: postgresql://${COMICS_DB_USER}:${COMICS_DB_PASSWORD}@comics-db:5432/${COMICS_DB_NAME}?schema=public

    ports:
      - "${COMICS_SERVICE_PORT}:3002"

    depends_on:
      comics-db:
        condition: service_healthy

    command:
      >
        sh -c "
        npx prisma migrate deploy &&
        npm run start:prod
        "

  # ==========================================
  # RENTALS DATABASE
  # ==========================================

  rentals-db:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${RENTALS_DB_USER}
      POSTGRES_PASSWORD: ${RENTALS_DB_PASSWORD}
      POSTGRES_DB: ${RENTALS_DB_NAME}

    ports:
      - "${RENTALS_DB_PORT}:5432"

    volumes:
      - rentals_db_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${RENTALS_DB_USER} -d ${RENTALS_DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  # ==========================================
  # RENTALS SERVICE
  # ==========================================

  rentals-service:
    build:
      context: ./services/rentals-service
    restart: unless-stopped

    environment:
      PORT: ${RENTALS_SERVICE_PORT}

      DATABASE_URL: postgresql+psycopg://${RENTALS_DB_USER}:${RENTALS_DB_PASSWORD}@rentals-db:5432/${RENTALS_DB_NAME}

      COMICS_SERVICE_URL: ${RENTALS_COMICS_SERVICE_URL}

      COPIES_SERVICE_URL: ${RENTALS_COPIES_SERVICE_URL}

      HTTP_TIMEOUT_SECONDS: ${RENTALS_HTTP_TIMEOUT_SECONDS}

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      RABBITMQ_RETURN_ROUTING_KEY: ${RABBITMQ_RETURN_ROUTING_KEY}

    ports:
      - "${RENTALS_SERVICE_PORT}:8001"

    depends_on:
      rentals-db:
        condition: service_healthy

      comics-service:
        condition: service_started

      copies-service:
        condition: service_started

      rabbitmq:
        condition: service_healthy

  # ==========================================
  # COPIES DATABASE
  # ==========================================

  copies-db:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${COPIES_DB_USER}
      POSTGRES_PASSWORD: ${COPIES_DB_PASSWORD}
      POSTGRES_DB: ${COPIES_DB_NAME}

    ports:
      - "${COPIES_DB_PORT}:5432"

    volumes:
      - copies_db_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${COPIES_DB_USER} -d ${COPIES_DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  # ==========================================
  # COPIES SERVICE
  # ==========================================

  copies-service:
    build:
      context: ./services/copies-service

    restart: unless-stopped

    environment:
      PORT: ${COPIES_SERVICE_PORT}

      DATABASE_URL: postgresql+psycopg://${COPIES_DB_USER}:${COPIES_DB_PASSWORD}@copies-db:5432/${COPIES_DB_NAME}

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      RABBITMQ_RETURN_QUEUE: ${RABBITMQ_RETURN_QUEUE}
      RABBITMQ_RETURN_ROUTING_KEY: ${RABBITMQ_RETURN_ROUTING_KEY}

    ports:
      - "${COPIES_SERVICE_PORT}:8002"

    depends_on:
      copies-db:
        condition: service_healthy


  # ==========================================
  # COPIES CONSUMER
  # ==========================================

  copies-consumer:
    build:
      context: ./services/copies-service

    restart: unless-stopped

    command:
      python -u -m app.messaging.consumer

    environment:
      DATABASE_URL: postgresql+psycopg://${COPIES_DB_USER}:${COPIES_DB_PASSWORD}@copies-db:5432/${COPIES_DB_NAME}

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      RABBITMQ_RETURN_QUEUE: ${RABBITMQ_RETURN_QUEUE}
      RABBITMQ_RETURN_ROUTING_KEY: ${RABBITMQ_RETURN_ROUTING_KEY}

    depends_on:
      copies-db:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy
        
  # ==========================================
  # API GATEWAY
  # ==========================================

  api-gateway:
    build:
      context: ./api-gateway

    restart: unless-stopped

    environment:
      PORT: ${GATEWAY_PORT}

      AUTH_SERVICE_URL: ${GATEWAY_AUTH_SERVICE_URL}

      COMICS_SERVICE_URL: ${GATEWAY_COMICS_SERVICE_URL}

      RENTALS_SERVICE_URL: ${GATEWAY_RENTALS_SERVICE_URL}

      COPIES_SERVICE_URL: ${GATEWAY_COPIES_SERVICE_URL}

      HTTP_TIMEOUT_MS: ${GATEWAY_HTTP_TIMEOUT_MS}

    ports:
      - "${GATEWAY_PORT}:3000"

    depends_on:
      auth-service:
        condition: service_started

      comics-service:
        condition: service_started

      rentals-service:
        condition: service_started

      copies-service:
        condition: service_started

  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  auth_db_data:
  comics_db_data:
  rentals_db_data:
  copies_db_data: 